services:
    cloudflare:
        image: cloudflare/cloudflared:latest
        restart: unless-stopped
        network_mode: host
        env_file: .env
        command: tunnel --no-autoupdate run --token ${token}
        
